apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
  namespace: dapr-demo
spec:
  type: secretstores.gcp.secretmanager
  version: v1
  metadata:
    - name: project_id
      value: "${GCP_PROJECT_ID}"
    - name: type
      value: "service_account"
