apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: dapr-config
  namespace: dapr-demo
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: ""
  metric:
    enabled: true
  logging:
    apiLogging:
      enabled: true
      obfuscateURLs: false
  mtls:
    enabled: true
    workloadCertTTL: "24h"
    allowedClockSkew: "15m"
  accessControl:
    defaultAction: allow
    trustDomain: "dapr-demo"
